### PR TITLE
UI

### PR DESCRIPTION
**Pull request by harshu0001**
<h1 align="center">UI with Neon Effects</h1>

Better Looking Page 
***
Screenshot 2023-10-04 015728

Good How to box 
***
Screenshot 2023-10-04 015742

### CODE REVIEW

**Comment by Alitindrawan24** [comment]
Great UI !! but the default one is more comfortable I see. I want to accept this PR but can you make the theme UI can be switchable ? like ligth and dark mode to make users can switch and choose the theme and make the normal one as default. Thank you

**Comment by harshu0001** [comment]
Ya sure!

**Comment by Alitindrawan24** [comment]
> Ya sure!

Any update on this PR ?

**Comment by harshu0001** [comment]
I'll get it done by today itself. 
Sorry for the delay!

**Pull request closed without merging**
